[workspace]
members = [
    "node",
    "runtime",
    "pallets/nft-marketplace",
    "pallets/property-governance",
    "pallets/property-management",
    "pallets/xcavate-whitelist",
]
resolver = "2"

[profile.release]
panic = "unwind"
